module.exports = ["Acil Yardım ve Afet",
    "Ağaç İşleri Endüstri Mühendisliği",
    "Aile ve Tüketici Bilimleri",
    "Aktüerya",
    "Alman Dili ve Edebiyatı",
    "Almanca Öğretmenliği",
    "Amerikan Kültürü ve Edebiyatı ",
    "Animasyon ",
    "Antrenörlük Eğitimi",
    "Antropoloji ",
    "Arap Dili ve Edebiyatı Bölümü Başarı Sıralaması ",
    "Arapça Öğretmenliği",
    "Arkeoloji",
    "Arnavut Dili ve Edebiyatı",
    "Astronomi ve Uzay Bilimleri ",
    "Avrupa Birliği İlişkileri",
    "Azerbaycan Dili ve Edebiyatı ",
    "Bahçe Bitkileri",
    "Balıkçılık Teknolojisi Mühendisliği Hakkında Bilgi İçin Tıklayınız ",
    "Bankacılık ",
    "Bankacılık ve Finans",
    "Bankacılık ve Finansman",
    "Basın ve Yayın",
    "Beden Eğitimi ve Spor Öğretmenliği",
    "Beslenme ve Diyetetik",
    "Bilgi ve Belge Yönetimi",
    "Bilgisayar Teknolojisi ve Bilişim Sistemleri",
    "Bilgisayar Bilimleri ve Mühendisliği",
    "Bilgisayar Mühendisliği",
    "Bilgisayar ve Enformasyon Sistemleri",
    "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği Hakkında Bilgi İçin Tıklayınız",
    "Bilgisayar ve Yazılım Mühendisliği Hakkında Bilgi İçin Tıklayınız ",
    "Bilgisayar-Enformatik",
    "Bilim Tarihi",
    "Bilişim Sistemleri Mühendisliği",
    "Bilişim Sistemleri ve Teknolojileri",
    "Bitki Koruma",
    "Bitkisel Üretim ve Teknolojileri​",
    "Biyoenformatik ve Genetik",
    "Biyokimya",
    "Biyoloji",
    "Biyoloji Öğretmenliği",
    "Biyomedikal Mühendisliği",
    "Biyomühendislik",
    "Biyosistem Mühendisliği",
    "Biyoteknoloji ile Biyoteknoloji ve Moleküler Biyoloji",
    "Boşnak Dili ve Edebiyatı",
    "Bulgar Dili ve Edebiyatı",
    "Canlandırma Filmi Tasarım ve Yönetimi",
    "Cevher Hazırlama Mühendisliği",
    "Coğrafya",
    "Coğrafya Öğretmenliği",
    "Çağdaş Türk Lehçeleri ve Edebiyatları",
    "Çağdaş Yunan Dili ve Edebiyatı",
    "Çalışma Ekonomisi ve Endüstri İlişkileri",
    "Çerkez Dili ve Edebiyatı",
    "Çeviribilim",
    "Çevre Mühendisliği",
    "Çin Dili ve Edebiyatı",
    "Çocuk Gelişimi",
    "Deniz İşletmeciliği ve Yönetimi",
    "Deniz Ulaştırma İşletme Mühendisliği",
    "Denizcilik İşletmeleri Yönetimi",
    "Deri Mühendisliği",
    "Dijital Oyun Tasarımı",
    "Dil ve Konuşma Terapisi",
    "Dilbilim",
    "Dini İlimler",
    "Diş Hekimliği Fakültesi",
    "Doğu Dilleri",
    "Ebelik",
    "Eczacılık Fakültesi",
    "Ekonometri",
    "Ekonomi",
    "Ekonomi ve Finans",
    "El Sanatları",
    "Elektrik Mühendisliği",
    "Elektrik-Elektronik Mühendisliği",
    "Elektronik Mühendisliği",
    "Elektronik ve Haberleşme Mühendisliği",
    "Endüstri Mühendisliği",
    "Endüstri Mühendisliği Programları",
    "Endüstri Tasarımı",
    "Endüstri Ürünleri Tasarımı",
    "Endüstri ve Sistem Mühendisliği",
    "Endüstriyel Tasarım",
    "Endüstriyel Tasarım Mühendisliği",
    "Enerji Sistemleri Mühendisliği",
    "Enerji ve Malzeme Mühendisliği",
    "Enerji Yönetimi",
    "Ergoterapi",
    "Ermeni Dili ve Edebiyatı",
    "Eski Yunan Dili ve Edebiyatı",
    "Enformasyon Teknolojileri",
    "Eşit Ağırlıklı Programlar",
    "Fars Dili ve Edebiyatı",
    "Felsefe",
    "Felsefe Grubu Öğretmenliği",
    "Fen Bilgisi Öğretmenliği",
    "Film Tasarım ve Yazarlık",
    "Film Tasarım ve Yönetmenliği",
    "Film Tasarımı",
    "Finansal Ekonometri",
    "Fizik",
    "Fizik Mühendisliği",
    "Fizik Öğretmenliği",
    "Fizyoterapi ve Rehabilitasyon",
    "Fotoğraf ve Video",
    "Fransız Dili ve Edebiyatı",
    "Fransızca Öğretmenliği",
    "Gastronomi",
    "Gastronomi ve Mutfak Sanatları",
    "Gayrimenkul ve Varlık Değerleme",
    "Gazetecilik",
    "Geleneksel Türk Sanatları (M.T.O.K.)",
    "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
    "Gemi Makineleri İşletme Mühendisliği",
    "Gemi ve Deniz Teknolojisi Mühendisliği",
    "Gemi ve Yat Tasarımı",
    "Genetik ve Biyomühendislik",
    "Geomatik Mühendisliği",
    "Gerontoloji",
    "Gıda Mühendisliği",
    "Gıda Teknolojisi",
    "Girişimcilik",
    "Görme Engelliler Öğretmenliği",
    "Görsel İletişim Tasarımı",
    "Görsel Sanatlar",
    "Görsel Sanatlar ve Görsel İletişim Tasarımı",
    "Grafik Tasarım",
    "Gümrük İşletme",
    "Gürcü Dili ve Edebiyatı",
    "Güverte",
    "Halkbilim",
    "Halkla İlişkiler",
    "Halkla İlişkiler ve Reklamcılık",
    "Halkla İlişkiler ve Tanıtım",
    "Harita Mühendisliği",
    "Havacılık Elektrik ve Elektroniği",
    "Havacılık İşletmeciliği",
    "Havacılık ve Uzay Mühendisliği",
    "Hayvansal Üretim",
    "Hemşirelik",
    "Hemşirelik ve Sağlık Hizmetleri",
    "Hidrojeoloji Mühendisliği",
    "Hindoloji",
    "Hititoloji",
    "Hukuk Fakültesi",
    "Hungaroloji",
    "İbrani Dili ve Edebiyatı",
    "İç Mimarlık",
    "İç Mimarlık ve Çevre Tasarımı",
    "İktisat",
    "İktisadi ve İdari Bilimler",
    "İlahiyat Fakültesi",
    "İletişim Bilimleri",
    "İletişim Sanatları",
    "İletişim Tasarımı",
    "İletişim Tasarımı ve Medya",
    "İletişim Tasarımı ve Yönetimi",
    "İletişim ve Tasarım",
    "İlköğretim Matematik Öğretmenliği",
    "İmalat Mühendisliği",
    "İngiliz Dil Bilimi",
    "İngiliz Dili ve Edebiyatı",
    "İngiliz Dili ve Karşılaştırmalı Edebiyat",
    "İngilizce Öğretmenliği",
    "İnsan Kaynakları Yönetimi",
    "İnsan ve Toplum Bilimleri",
    "İnşaat Mühendisliği",
    "İslam Bilimleri",
    "İslam ve Din Bilimleri",
    "İslami İlimler",
    "İspanyol Dili ve Edebiyatı",
    "İstatistik",
    "İstatistik ve Bilgisayar Bilimleri",
    "İş Sağlığı ve Güvenliği",
    "İşitme Engelliler Öğretmenliği",
    "İşletme",
    "İşletme Bilgi Yönetimi",
    "İşletme Enformatiği",
    "İşletme Mühendisliği",
    "İşletme Yönetimi",
    "İşletme-Ekonomi",
    "İtalyan Dili ve Edebiyatı",
    "Japon Dili ve Edebiyatı",
    "Japonca Öğretmenliği",
    "Jeofizik Mühendisliği",
    "Jeoloji Mühendisliği",
    "Kamu Yönetimi",
    "Kanatlı Hayvan Yetiştiriciliği",
    "Karşılaştırmalı Edebiyat",
    "Kazak Dili ve Edebiyatı",
    "Kentsel Tasarım ve Peyzaj",
    "Kentsel Tasarım ve Peyzaj Mimarlığı",
    "Kimya",
    "Kimya Mühendisliği",
    "Kimya Mühendisliği ve Uygulamalı Kimya",
    "Kimya Öğretmenliği",
    "Kimya ve Süreç Mühendisliği",
    "Kimya-Biyoloji Mühendisliği",
    "Klasik Arkeoloji",
    "Konaklama İşletmeciliği",
    "Konaklama ve Turizm İşletmeciliği",
    "Kontrol ve Otomasyon Mühendisliği",
    "Kore Dili ve Edebiyatı",
    "Kurgu-Ses ve Görüntü Yönetimi",
    "Kuyumculuk ve Mücevher Tasarımı",
    "Kültür Varlıklarını Koruma ve Onarım",
    "Küresel Siyaset ve Uluslararası İlişkiler",
    "Kürt Dili ve Edebiyatı",
    "Latin Dili ve Edebiyatı",
    "Leh Dili ve Edebiyatı",
    "Lif ve Polimer Mühendisliği",
    "Lojistik",
    "Lojistik ve Taşımacılık",
    "Lojistik Yönetimi",
    "Maden Mühendisliği",
    "Makine Mühendisliği",
    "Makine ve İmalat Mühendisliği",
    "Makine ve Malzeme Mühendisliği",
    "Maliye",
    "Malzeme Bilimi ve Mühendisliği",
    "Malzeme Bilimi ve Nanoteknoloji Mühendisliği",
    "Malzeme Mühendisliği",
    "Matematik",
    "Matematik Mühendisliği",
    "Matematik Öğretmenliği",
    "Matematik ve Bilgisayar Bilimleri",
    "Matematik-Bilgisayar",
    "Medya ve Görsel Sanatlar",
    "Medya ve İletişim",
    "Medya ve İletişim Sistemleri",
    "Mekatronik Mühendisliği",
    "Mekatronik Sistemler Mühendisliği",
    "Metalurji ve Malzeme Mühendisliği",
    "Meteoroloji Mühendisliği",
    "Mimarlık",
    "Mobilya Üretimi ve İç Mekan Tasarımı",
    "Moda Tasarımı",
    "Moda ve Tekstil Tasarımı",
    "Moleküler Biyoloji ve Genetik",
    "Muhasebe",
    "Muhasebe Bilgi Sistemleri",
    "Muhasebe ve Denetim",
    "Muhasebe ve Finans Yönetimi",
    "Mücevherat Mühendisliği",
    "Mühendislik Programları",
    "Mühendislik ve Doğa Bilimleri Programları",
    "Mütercim-Tercümanlık",
    "Müzecilik",
    "Nanoteknoloji Mühendisliği",
    "Nükleer Enerji Mühendisliği",
    "Odyoloji",
    "Okul Öncesi Öğretmenliği",
    "Optik ve Akustik Mühendisliği",
    "Organik Tarım İşletmeciliği",
    "Orman Endüstrisi Mühendisliği",
    "Orman Mühendisliği",
    "Ortez-Protez",
    "Otel Yöneticiliği",
    "Otomotiv Mühendisliği",
    "Öğretmenlik Programları",
    "Özel Eğitim Öğretmenliği",
    "Pazarlama",
    "Perfüzyon",
    "Petrol ve Doğalgaz Mühendisliği",
    "Peyzaj Mimarlığı",
    "Pilot Eğitimi",
    "Pilotaj",
    "Polimer Mühendisliği",
    "Polonya Dili ve Kültürü",
    "Protohistorya",
    "Protohistorya ve Ön Asya Arkeolojisi",
    "Psikoloji",
    "Psikolojik Danışmanlık ve Rehberlik",
    "Radyo ve Televizyon",
    "Radyo, Televizyon ve Sinema",
    "Raylı Sistemler Mühendisliği",
    "Rehberlik ve Psikolojik Danışmanlık",
    "Reklam Tasarımı ve İletişimi",
    "Reklamcılık",
    "Reklamcılık ve Halkla İlişkiler",
    "Rekreasyon",
    "Rekreasyon Yönetimi",
    "Restorasyon ve Konservasyon",
    "Rus Dili Öğretmenliği",
    "Rus Dili ve Edebiyatı",
    "Rus Dili ve Edebiyatı Öğretmenliği",
    "Rus Dili ve Öğretmenliği",
    "Rus ve İngiliz Dilleri ve Edebiyatları",
    "Sağlık İdaresi",
    "Sağlık Yönetimi",
    "Sanat Tarihi",
    "Sanat ve Kültür Yönetimi",
    "Sanat ve Sosyal Bilimler Programları",
    "Sanat Yönetimi",
    "Sermaye Piyasaları ve Portföy Yönetimi",
    "Sermaye Piyasası",
    "Seyahat İşletmeciliği",
    "Seyahat İşletmeciliği ve Turizm Rehberliği",
    "Sınıf Öğretmenliği",
    "Sigortacılık",
    "Sigortacılık ve Risk Yönetimi",
    "Sigortacılık ve Sosyal Güvenlik",
    "Sinema ve Dijital Medya",
    "Sinema ve Televizyon",
    "Sinoloji",
    "Sivil Hava Ulaştırma İşletmeciliği",
    "Sivil Havacılık İşletmeciliği",
    "Siyasal Bilimler",
    "Siyaset Bilimi",
    "Siyaset Bilimi ve Kamu Yönetimi",
    "Siyaset Bilimi ve Uluslararası İlişkiler",
    "Sosyal Bilgiler Öğretmenliği",
    "Sosyal Hizmet",
    "Sosyal ve Siyasal Bilimler",
    "Sosyoloji",
    "Spor Yöneticiliği",
    "Su Ürünleri Mühendisliği",
    "Sümeroloji",
    "Süt Teknolojisi",
    "Şehir ve Bölge Planlama",
    "Takı Tasarımı",
    "Tapu Kadastro",
    "Tarım Ekonomisi",
    "Tarım Makineleri ve Teknolojileri Mühendisliği",
    "Tarımsal Biyoteknoloji",
    "Tarımsal Genetik Mühendisliği",
    "Tarımsal Yapılar ve Sulama",
    "Tarih",
    "Tarih Öğretmenliği",
    "Tarih Öncesi Arkeolojisi",
    "Tarla Bitkileri",
    "Teknoloji ve Bilgi Yönetimi",
    "Tekstil Mühendisliği",
    "Tekstil Tasarımı",
    "Tekstil ve Moda Tasarımı",
    "Televizyon Haberciliği ve Programcılığı",
    "Tıp Fakültesi",
    "Tıp Mühendisliği",
    "Toprak Bilimi ve Bitki Besleme",
    "Turizm İşletmeciliği",
    "Turizm İşletmeciliği ve Otelcilik",
    "Turizm Rehberliği",
    "Turizm ve Otel İşletmeciliği",
    "Turizm ve Otelcilik",
    "Turizm ve Otel Yöneticiliği",
    "Türk Dili ve Edebiyatı",
    "Türk Dili ve Edebiyatı Öğretmenliği",
    "Türk Halkbilimi",
    "Türk İslam Arkeolojisi",
    "Türkçe Öğretmenliği",
    "Türkoloji",
    "Tütün Eksperliği Yüksekokulu",
    "Uçak Elektrik-Elektronik",
    "Uçak Gövde-Motor",
    "Uçak Gövde-Motor Bakım",
    "Uçak Mühendisliği",
    "Uçak ve Uzay Mühendisliği",
    "Ulaştırma Mühendisliği",
    "Ulaştırma ve Lojistik",
    "Uluslararası Finans",
    "Uluslararası Finans ve Bankacılık",
    "Uluslararası Girişimcilik",
    "Uluslararası İlişkiler",
    "Uluslararası İşletme",
    "Uluslararası İşletme Yönetimi",
    "Uluslararası İşletmecilik",
    "Uluslararası İşletmecilik ve Ticaret",
    "Uluslararası Lojistik",
    "Uluslararası Lojistik ve Taşımacılık",
    "Uluslararası Lojistik Yönetimi",
    "Uluslararası Perakende Yönetimi",
    "Uluslararası Ticaret",
    "Uluslararası Ticaret ve Finans",
    "Uluslararası Ticaret ve Finansman",
    "Uluslararası Ticaret ve İşletmecilik",
    "Uluslararası Ticaret ve Lojistik",
    "Uluslararası Ticaret ve Lojistik Yönetimi",
    "Uluslararası Ticaret ve Pazarlama",
    "Uluslararası Ticaret, Lojistik ve İşletmecilik",
    "Urdu Dili ve Edebiyatı",
    "Uzay Bilimleri ve Teknolojileri",
    "Uzay Mühendisliği",
    "Üstün Zekalılar Öğretmenliği",
    "Veteriner Fakültesi",
    "Yaban Hayatı Ekolojisi ve Yönetimi",
    "Yazılım Mühendisliği",
    "Yeni Medya",
    "Yeni Medya ve Gazetecilik",
    "Yerel Yönetimler",
    "Yiyecek ve İçecek İşletmeciliği",
    "Yönetim Bilimleri Programları",
    "Yönetim Bilişim Sistemleri",
    "Yunan Dili ve Edebiyatı",
    "Zaza Dili ve Edebiyatı",
    "Zihin Engelliler Öğretmenliği",
    "Zootekni",
    "Acil Durum ve Afet Yönetimi",
    "Adalet",
    "Ağız ve Diş Sağlığı",
    "Alternatif Enerji Kaynakları Teknolojisi",
    "Ameliyathane Hizmetleri",
    "Anestezi",
    "Arıcılık",
    "Aşçılık",
    "Ayakkabı Tasarım ve Üretimi",
    "Bağcılık",
    "Bahçe Tarımı",
    "Bankacılık ve Sigortacılık",
    "Basım ve Yayın Teknolojileri",
    "Basın ve Yayıncılık",
    "Beton Teknolojisi",
    "Bilgi Yönetimi",
    "Bilgisayar Destekli Tasarım ve Animasyon",
    "Bilgisayar Operatörlüğü",
    "Bilgisayar Programcılığı",
    "Bilgisayar Teknolojisi",
    "Bitki Koruma",
    "Biyomedikal Cihaz Teknolojisi",
    "Boya Teknolojisi",
    "Büro Yönetimi ve Yönetici Asistanlığı",
    "Coğrafi Bilgi Sistemleri",
    "Çağrı Merkezi Hizmetleri",
    "Çay Tarımı ve İşleme Teknolojisi",
    "Çevre Koruma ve Kontrol",
    "Çevre Sağlığı",
    "Çevre Temizliği ve Denetimi",
    "Çim Alan Tesisi ve Yönetimi",
    "Çocuk Gelişimi",
    "Çorap ve Moda Tasarımı",
    "Deniz Ulaştırma ve İşletme",
    "Deniz ve Liman İşletmeciliği",
    "Deri Konfeksiyon",
    "Deri Teknolojisi",
    "Dış Ticaret",
    "Diş Protez Teknolojisi",
    "Diyaliz",
    "Doğalgaz ve Tesisatı Teknolojisi",
    "Doğal Yapı Taşları Teknolojisi",
    "Döküm",
    "Eczane Hizmetleri",
    "Elektrik",
    "Elektrik Enerjisi Üretim İletim ve Dağıtımı",
    "Elektrik Cihaz Teknolojisi",
    "Elektronik Haberleşme Teknolojisi",
    "Elektromekanik Taşıyıcılar",
    "Elektronik Teknolojisi",
    "Elektronörofizyoloji",
    "Emlak ve Emlak Yönetimi",
    "Endüstri Ürünleri Tasarımı",
    "Endüstriyel Bitkiler Yetiştiriciliği",
    "Endüstriyel Cam ve Seramik",
    "Endüstriyel Kalıpçılık",
    "Endüstriyel Tavukçuluk",
    "Enerji Tesisleri İşletmeciliği",
    "Engelli Bakımı ve Rehabilitasyon",
    "Eser Koruma",
    "Et ve Ürünleri Teknolojisi",
    "Ev İdaresi",
    "Evde Hasta Bakımı",
    "Fındık Eksperliği",
    "Fidan Yetiştiriciliği",
    "Fizyoterapi",
    "Fotoğrafçılık ve Kameramanlık",
    "Gaz ve Tesisatı Teknolojisi",
    "Geleneksel El Sanatları",
    "Gemi İnşaatı",
    "Gemi Makineleri İşletme",
    "Geoteknik",
    "Gıda Kalite Kontrolü ve Analizi",
    "Gıda Teknolojisi",
    "Giyim Üretim Teknolojisi",
    "Görsel İletişim",
    "Grafik Tasarımı",
    "Halıcılık ve Kilimcilik",
    "Halkla İlişkiler ve Tanıtım",
    "Harita ve Kadastro",
    "Hava Lojistiği",
    "Havacılıkta Yer Hizmetleri Yönetimi",
    "İç Mekan Tasarımı",
    "İklimlendirme ve Soğutma Teknolojisi",
    "İkram Hizmetleri",
    "İlahiyat (Önlisans)",
    "İlk ve Acil Yardım",
    "İnsan Kaynakları Yönetimi",
    "İnşaat Teknolojisi",
    "İnternet ve Ağ Teknolojileri",
    "İş Makinaları Operatörlüğü",
    "İşçi Sağlığı ve İş Güvenliği",
    "İş Sağlığı ve Güvenliği",
    "İş ve Uğraşı Terapisi",
    "İşletme Yönetimi",
    "Kağıt Teknolojisi",
    "Kaynak Teknolojisi",
    "Kesme Çiçek Yetiştiriciliği",
    "Kimya Teknolojisi",
    "Kontrol ve Otomasyon Teknolojisi",
    "Kooperatifçilik",
    "Kozmetik Teknolojisi",
    "Kuruyemiş Üretimi ve Teknolojisi",
    "Kuyumculuk ve Takı Tasarımı",
    "Kültürel Miras ve Turizm",
    "Kümes Hayvanları Yetiştiriciliği",
    "Laborant ve Veteriner Sağlık",
    "Laboratuvar Teknolojisi",
    "Lastik ve Plastik Teknolojisi",
    "Lojistik",
    "Maden Teknolojisi",
    "Makine",
    "Makine, Resim ve Konstrüksiyon",
    "Maliye",
    "Mantarcılık",
    "Marina İşletme",
    "Marka İletisimi (Açikögretim)",
    "Medya ve İletişim",
    "Mekatronik",
    "Menkul Kıymetler ve Sermaye Piyasası",
    "Metalürji",
    "Meyve ve Sebze İşleme Teknolojisi",
    "Mimari Dekoratif Sanatlar",
    "Mimari Restorasyon",
    "Mobil Teknolojileri",
    "Mobilya ve Dekorasyon",
    "Moda Tasarımı",
    "Muhasebe ve Vergi Uygulamaları",
    "Nükleer Teknoloji ve Radyasyon Güvenliği",
    "Nükleer Tıp Teknikleri",
    "Odyometri",
    "Organik Tarım",
    "Ormancılık ve Orman Ürünleri",
    "Ortopedik Protez ve Ortez",
    "Oto Boya ve Karoseri",
    "Otobüs Kaptanlığı",
    "Otomotiv Teknolojisi",
    "Otopsi Yardımcılığı",
    "Patoloji Laboratuvar Teknikleri",
    "Pazarlama",
    "Perakende Satış ve Mağaza Yönetimi",
    "Perfüzyon Teknikleri",
    "Peyzaj ve Süs Bitkileri",
    "Podoloji",
    "Posta Hizmetleri",
    "Radyo ve Televizyon Programcılığı",
    "Radyo ve Televizyon Teknolojisi",
    "Radyoterapi",
    "Rafineri ve Petro",
    "Raylı Sistemler Elektrik ve Elektronik Teknolojisi",
    "Raylı Sistemler İşletmeciliği",
    "Raylı Sistemler Makine Teknolojisi",
    "Raylı Sistemler Makinistlik",
    "Raylı Sistemler Yol Teknolojisi",
    "Reklamcılık",
    "Saç Bakımı ve Güzellik Hizmetleri",
    "Sağlık Kurumları İşletmeciliği",
    "Sahne ve Gösteri Sanatları Teknolojisi",
    "Seracılık",
    "Seramik, Cam ve Çinicilik",
    "Sivil Hava Ulaştırma İşletmeciliği",
    "Sivil Havacılık Kabin Hizmetleri",
    "Sondaj Teknolojisi",
    "Sosyal Güvenlik",
    "Sosyal Hizmetler",
    "Spor Yönetimi",
    "Su Altı Teknolojisi",
    "Su Ürünleri İşleme Teknolojisi",
    "Sulama Teknolojisi",
    "Süs Bitkileri Yetiştiriciliği",
    "Süt ve Besi Hayvancılığı",
    "Süt ve Ürünleri Teknolojisi",
    "Tahribatsız Muayene",
    "Tapu ve Kadastro",
    "Tarım (Açıköğretim)",
    "Tarım İşletmecilik",
    "Tarım Makineleri",
    "Tarımsal Ürünler Muhafaza ve Depolama Teknolojisi",
    "Tarla Bitkileri",
    "Tekstil Teknolojisi",
    "Tıbbi Dokümantasyon ve Sekreterlik",
    "Tıbbi Görüntüleme Teknikleri",
    "Tıbbi Laboratuvar Teknikleri",
    "Tıbbi Tanıtım ve Pazarlama",
    "Tıbbi ve Aromatik Bitkiler",
    "Tohumculuk",
    "Turist Rehberliği",
    "Turizm Animasyonu",
    "Turizm Rehberliği",
    "Turizm ve Otel İşletmeciliği",
    "Turizm ve Seyahat Hizmetleri",
    "Uçak Teknolojisi",
    "Ulaştırma ve Trafik Hizmetleri",
    "Un ve Unlu Mamuller Teknolojisi",
    "Üretimde Kalite Kontrol",
    "Yağ Endüstrisi",
    "Yapı Denetimi Bölümü",
    "Yapı Ressamlığı",
    "Yapı Tesisat Teknolojisi",
    "Yapı Yalıtım Teknolojisi",
    "Yaşlı Bakımı",
    "Yat İşletme ve Yönetimi",
    "Yat Kaptanlığı",
    "Yem Teknolojisi ve Hayvan Besleme",
    "Yerel Yönetimler",
    "Zeytincilik ve Zeytin İşleme Teknolojisi"
]